### ISSUE TITLE
Keep persistent peer id between deployments

### ISSUE THREAD

**Issue by v-stickykeys** [ceramicnetwork/js-ipfs-daemon#14]
Right now there is an issue with the config file that we store in S3. It seems that pubsub messages only get transferred to the node when we delete this file. After deletion it is not regenerated unless the instance is restarted. When this restart happens a new peer id is created.

We want to save keys so that the peer id stays the same between deployments

**Comment by zachferland** [comment]
yup, shouldn't have to delete config often, but may want to and would be nice load key from secrets somewhere at start instead of a config file including all configs

**Comment by v-stickykeys** [comment]
I think we can close this now bc we no longer need to delete the config file
